apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis-dev
  namespace: instavote-dev
spec:
  sourceRef:
    kind: GitRepository
    name: instavote
  path: "./deploy/redis"
  targetNamespace: instavote-dev
  interval: 1m
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: redis
      namespace: instavote-dev
