apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vote
  namespace: instavote
spec:
  interval: 1m
  targetNamespace: instavote
  sourceRef:
    kind: GitRepository
    name: instavote
  path: "./deploy/vote"
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: vote
      namespace: instavote
