apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vote-dev
  namespace: instavote-dev
spec:
  sourceRef:
    kind: GitRepository
    name: instavote
  path: "./deploy/vote"
  targetNamespace: instavote-dev
  dependsOn:
    - name: redis-dev
  interval: 1m
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: vote
      namespace: instavote-dev
