apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vote
  namespace: instavote
spec:
  interval: 1m
  targetNamespace: instavote
  sourceRef:
    kind: GitRepository
    name: instavote
  path: "./deploy/vote"
  prune: true
