apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: db
  namespace: instavote-staging
spec:
  chart:
    spec:
      chart: postgres
      version: 0.2.11
      sourceRef:
        kind: HelmRepository
        name: lfs269
  targetNamespace: instavote-staging
  interval: 1m
  values:
    service:
      name: db
    settings:
      authMethod: trust

