apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: result-staging
  namespace: instavote-staging
spec:
  chart:
    spec:
      chart: ./deploy/charts/result
      sourceRef:
        kind: GitRepository
        name: instavote-staging
      reconcileStrategy: Revision
  targetNamespace: instavote-staging
  interval: 1m

