apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: slack-notifications
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: "*"
      namespace: instavote-dev
    - kind: GitRepository
      name: "*"
      namespace: instavote-dev
    - kind: HelmRelease
      name: "*"
      namespace: instavote-dev
    - kind: Kustomization
      name: "*"
      namespace: instavote-staging
    - kind: GitRepository
      name: "*"
      namespace: instavote-staging
    - kind: HelmRelease
      name: "*"
      namespace: instavote-staging
