apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: vote-staging
  namespace: flux-system
spec:
  providerRef:
    name: github-instavote
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: vote-staging
      namespace: instavote-staging
