apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vote-staging
  namespace: instavote-staging
spec:
  sourceRef:
    kind: GitRepository
    name: instavote-staging
  path: ./deploy/vote/overlays/staging
  targetNamespace: instavote-staging
  dependsOn:
    - name: redis-staging
  interval: 1m
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: vote
      namespace: instavote-staging
