apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: result-dev
  namespace: instavote-dev
spec:
  chart:
    spec:
      chart: ./deploy/charts/result
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: instavote-dev
  targetNamespace: instavote-dev
  interval: 1m

